version: "3.9"
services:
  backend:
        hostname: backend
        build: ./backend
        ports:
            - "9090:9090"
        expose:
            - 9090
        volumes:
            - "./backend:/home/app"
        command: ./back-end
        networks:
            - main-network
        env_file:
            - ./backend/.env
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
networks:
  main-network:
    name: project-external-network
    external: true